// Generated by CoffeeScript 1.10.0
var common, through;

through = require('through2');

common = require('./common.js');

module.exports.list = function(options) {
  var config, opt, past, ref, transform;
  ref = common.prepare(options), opt = ref[0], config = ref[1];
  config.available = [];
  transform = function(file, enc, cb) {
    var block, filename, found, i, j, len, len1, name, pack, ref1, ref2;
    found = false;
    filename = file.relative.replace(/\\/g, '/');
    ref1 = ['js', 'css'];
    for (i = 0, len = ref1.length; i < len; i++) {
      block = ref1[i];
      for (pack in config[block]) {
        ref2 = config[block][pack];
        for (j = 0, len1 = ref2.length; j < len1; j++) {
          name = ref2[j];
          if (name === filename) {
            found = true;
          }
        }
      }
    }
    if (!found) {
      config.available.push(filename);
    }
    return cb(null, file);
  };
  past = function(cb) {
    common.saveConfig(opt.configFile, config);
    return cb();
  };
  return through.obj(transform, past);
};
